version: '2'

services:
  postgres:
    image: postgres
    container_name: sandbox-postgres
    volumes:
     - postgresql:/var/lib/postgresql/data:delegated
    ports:
     - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    logging:
      driver: none

  app:
    build: .
    container_name: sandbox-app
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - .:/sandbox
    ports:
    - "3000:3000"
    depends_on:
    - postgres

volumes:
  postgresql:
