version: '3.9'

services:
  db:
    image: postgres
    container_name: aspc-postgres
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password

  web:
    build: .
    container_name: aspc-rails
    volumes:
    - .:/aspc:Z
    ports:
    - "3000:3000"
    depends_on:
    - db

  proxy:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - web 
      - wiki 
    ports:
      - "80:80"
      - "443:443"

  wikidb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wiki-data:/var/lib/postgresql/data
 
  
  wiki:
    image: requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "2000:3000"

volumes:
  pgdata:
  wiki-data: