version: '3.9'

services:
  db:
    image: postgres
    container_name: aspc-postgres
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password

  web:
    build: .
    container_name: aspc-rails
    volumes:
    - .:/aspc:Z
    ports:
    - "3000:3000"
    depends_on:
    - db

volumes:
  pgdata: